### ISSUE TITLE
Where do I get master.json

### ISSUE THREAD

**Issue by moselhy** [shrumit/Western-Timetable-Maker#2]
Is there a script where you're using to make master.json? The only way I see of making this is parsing content of https://studentservices.uwo.ca/secure/timetables/mastertt/ttindex.cfm for each subject, then for each subject I find each course by finding the h4 tags in the html content

**Comment by shrumit** [comment]
I should get around to filling out the Readme!

Scrapping is done by this program:
https://github.com/shrumit/timetable-scraper-java

**Comment by moselhy** [comment]
Thank you 🙏 will try it later

Kind regards,
Mohamed Moselhy

On Oct 20, 2019, at 18:29, Shrumit Mehta <notifications@github.com> wrote:

﻿

I should get around to filling out the Readme!

Scrapping is done by this program:
https://github.com/shrumit/timetable-scraper-java
